import type { sessionDetails } from "@/Utils/Types";
import { X } from "lucide-react";
import moment from "moment";
import { useRef } from "react";

type props = {
  session: sessionDetails;
};

const ReportViewModal = ({ session }: props) => {
  const modal = useRef<HTMLDialogElement>(null);
  const openModal = () => modal.current?.showModal();
  const closeModal = () => modal.current?.close();

  return (
    <div className="">
      <button
        onClick={() => openModal()}
        className="btn btn-ghost btn-md md:btn-lg hover:bg-transparent hover:border-none font-bold hover:text-white"
      >
        View Report
      </button>
      <dialog id="my_modal_2" ref={modal} className="modal ">
        <div className="modal-box  min-w-[300px] md:min-w-[600px] max-h-[600px] rounded-2xl overflow-y-scroll">
          <button
            onClick={() => closeModal()}
            className="btn btn-ghost btn-circle absolute right-2 top-2"
          >
            <X className="size-10" />{" "}
          </button>
          <h3 className="font-bold text-2xl text-center">
            Medical AI Agent Report
          </h3>
          <div className="flex flex-col justify-start items-start mt-10">
            {/* Session Info */}
            <h4 className="text-2xl text-blue-600 font-bold border-b-2 border-blue-500 w-full text-left">
              Session Info:
            </h4>
            <div className="mt-5 text-left">
              <p className="text-md">
                AI Agent:{" "}
                <span className="text-gray-500">
                  {session.selectedDoctor.specialist}
                </span>
              </p>
              <p className="text-md">
                Consultation Date:{" "}
                <span className="text-gray-500">
                  {moment(new Date(session.createdOn)).format("LLLL")}
                </span>
              </p>
              <p className="text-md">
                User:{" "}
                <span className="text-gray-500">{session.report?.user}</span>
              </p>
            </div>
            {/* Chief Complaint */}
            <h4 className="mt-5 text-2xl text-blue-600 font-bold border-b-2 border-blue-500 w-full text-left">
              Chief Complaint:
            </h4>
            <div className="mt-5 text-left">
              <p className="text-md">
                <span className="text-gray-500">
                  {session.report?.chiefComplaint}
                </span>
              </p>
            </div>
            {/* Summary */}
            <h4 className="mt-5 text-2xl text-blue-600 font-bold border-b-2 border-blue-500 w-full text-left">
              Summary:
            </h4>
            <div className="mt-5 text-left">
              <p className="text-md">
                <span className="text-gray-500">{session.report?.summary}</span>
              </p>
            </div>
            {/* Symptoms */}
            <h4 className="mt-5 text-2xl text-blue-600 font-bold border-b-2 border-blue-500 w-full text-left">
              Symptoms:
            </h4>
            <div className="mt-5 text-left">
              <p className="text-md">
                <span className="text-gray-500">
                  {session.report?.symptoms.join(", ")}
                </span>
              </p>
            </div>
            {/* Duration and Severity */}
            <h4 className="mt-5 text-2xl text-blue-600 font-bold border-b-2 border-blue-500 w-full text-left">
              Duration and Severity:
            </h4>
            <div className="mt-5 text-center grid grid-cols-2 gap-2 w-full">
              <p className="text-md">
                Duration:{" "}
                <span className="text-gray-500">
                  {session.report?.duration}
                </span>
              </p>
              <p className="text-md">
                Severity:{" "}
                <span className="text-gray-500">
                  {session.report?.severity}
                </span>
              </p>
            </div>
          </div>

          <div className="mt-10">
            <span className="text-red-500 ">
              This report is generated by AI and is for informational purposes
              Only. Check a real doctor if you need help.
            </span>
          </div>
        </div>
        <form method="dialog" className="modal-backdrop">
          <button></button>
        </form>
      </dialog>
    </div>
  );
};

export default ReportViewModal;
